## Nut Butter Sales (Dot product example)

In [1]:
import numpy as np
import pandas as pd

### Recreate the table below to find Total Sales

![](numpy_exercise_nut_butter_sales.png)

## Number of jars sold

In [2]:
np.random.seed(0)
# Number of jars sold
sales_amounts = np.random.randint(20, size=(5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [3]:
# Create weekly_sales DataFrame
weekly_sales = pd.DataFrame(sales_amounts,
                            index=['Mon', 'Tues', 'Wed', 'Thurs', 'Fri'],
                            columns=['Almond Butter', 'Peanut Butter', 'Cashew Butter'])
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

## Create prices array

In [4]:
prices = np.array([10, 8, 12])
prices

array([10,  8, 12])

## Create butter_prices DataFrame

In [5]:
# DOES NOT WORK!
# butter_prices = pd.DataFrame(prices,
#                             index=['Price'],
#                             columns=['Almond Butter', 'Peanut Butter', 'Cashew Butter'])

# ERROR => ValueError: Shape of passed values is (3, 1), indices imply (1, 3)

In [6]:
prices.shape

(3,)

In [7]:
# use reshape
butter_prices = pd.DataFrame(prices.reshape(1,3),
                             index=['Price'], #row 
                             columns=['Almond Butter', 'Peanut Butter', 'Cashew Butter'])
butter_prices

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [8]:
prices.shape, sales_amounts.shape

((3,), (5, 3))

- Numbers on inside must match
- Result => Outside numbers 

## Get Total Sales => Dot product of prices and sales amounts

In [9]:
total_sales = prices.dot(sales_amounts)

ValueError: shapes (3,) and (5,3) not aligned: 3 (dim 0) != 5 (dim 0)

In [10]:
# Shapes aren't aligned, let's Transpose
total_sales = prices.dot(sales_amounts.T)
total_sales

array([240, 138, 458, 232, 142])

## Create daily_sales

In [11]:
butter_prices

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [12]:
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [13]:
butter_prices.shape, weekly_sales.shape

((1, 3), (5, 3))

In [14]:
weekly_sales.T.shape

(3, 5)

In [15]:
# Flip weekly_sales so numbers on insides match
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales

Mon  Tues  Wed  Thurs  Fri
Price  240   138  458    232  142

## Add Total to weekly_sales DataFrame

In [16]:
type(weekly_sales)

pandas.core.frame.DataFrame

In [17]:
# DOES NOT WORK! Not the right shape.
# weekly_sales['Total ($)'] = daily_sales

# ERROR => alueError: Wrong number of items passed 5, placement implies 1
# Because we are trying to set a row (daily_sales) as column (on weekly_sales)

In [18]:
weekly_sales['Total ($)'] = daily_sales.T
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter  Total ($)
Mon               12             15              0        240
Tues               3              3              7        138
Wed                9             19             18        458
Thurs              4              6             12        232
Fri                1              6              7        142